### ISSUE TITLE
Pushing only conent of a folder rather than whole project

### ISSUE THREAD

**Issue by smohadjer** [markomarkovic/simple-php-git-deploy#41]
I want to automatically update a live site whenever I push changes to my repository and everything that should go live is inside a "dist" folder on github. Is there any way to specify only content of this folder to be pushed to live site  (preferably via a setting in deploy-config.php)? I see an option for excluding files/folders in config file, but not for including.

**Comment by easingthemes** [comment]
Hi,
could you reconsider this?

It's quite common to have large codebase in dev environment and to deploy only few files to production.
Eg, I have ReactJS project with over 200 files in development environment, and I will deploy only 2 files in production.

Thanks
