### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Icedroid** [markomarkovic/simple-php-git-deploy#45]
I have set timeout for   set_time_limit(30);  OR  set_time_limit(300000);
But It always  504 Gateway Time-out.

**Comment by markomarkovic** [comment]
I think that your PHP process is being run as a fastcgi so the PHP is probably getting executed as expected, but the httpd is not waiting for it to return the data before it abandons the request. For example [fastcgi_read_timeout](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout) for nginx.
