### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rosco1502** [markomarkovic/simple-php-git-deploy#46]
When I run the script, (some of the time) it shows
" Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@thelocken.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."
After taking an extremely long time to load, I'm not sure if this is simple-php-git-deploy's problem but its halting all my developing. If it is, I would be grateful if you could fix it. Thanks.

EDIT: When it happens to load, it shows
" Error encountered!
Stopping the script to prevent possible data loss.
CHECK THE DATA IN YOUR TARGET DIR!"
but when I check the target dir, it is completely intact compared to the github repo.

**Comment by markomarkovic** [comment]
Sorry, not much I can do. You need to determine exactly which step is failing and debug from that point on.
