### ISSUE TITLE
is this same as on codecanyon?

### ISSUE THREAD

**Issue by sambuev** [markomarkovic/simple-php-git-deploy#47]
Hello, I've found link on codecanyon, is this same?
http://codecanyon.net/item/easy-git-code-deploy/8586366

**Comment by markomarkovic** [comment]
The [configuration](http://ntknetworks.com/support/git-code-deploy/2-script-configuration/) for it looks different, so I don't think it's the same. Judging by the configuration, my project looks better to me ;)
