### ISSUE TITLE
Permission denied on private repository (SSH keys added)

### ISSUE THREAD

**Issue by micjamking** [markomarkovic/simple-php-git-deploy#53]
I'm using a private repository. I've already added my SSH keys and am able to do run git pull/push commands on my server (Amazon Linux) as the root user but looking to integrate with Github's webhooks using this plugin.

I've confirmed that my `SECRET_ACCESS_TOKEN`, `REMOTE_REPOSITORY`, `BRANCH`, and `TARGET_DIR` variables in my **deploy-config.php** are correct.

```html
Checking the environment ...

Running as apache.

/usr/bin/git: git version 2.1.0
/usr/bin/rsync: rsync  version 3.0.6  protocol version 30

Environment OK.

Deploying git@github.com:<username>/<project-name>.git branch
to        /var/www/html/<project-name>/ ...


$ git clone --depth=1 --branch <branch> git@github.com:<username>/<project-name>.git /tmp/spgd-2cf28dc8d59c3eb61947660c8a9d13c5/
Cloning into '/tmp/spgd-2cf28dc8d59c3eb61947660c8a9d13c5'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error encountered!
Stopping the script to prevent possible data loss.
CHECK THE DATA IN YOUR TARGET DIR!
```

Again, I'm able to run all git commands as the root user without problem. I'm also able to run [this similar script](https://gist.github.com/oodavid/1809044) without issue, but noticed that yours seemed more secure and wanted to give that a try.

Any help here would be appreciated.

**Comment by markomarkovic** [comment]
You're able to clone the repo as the `root` user, but the script is running as `apache` so it probably doesn't have access to the correct ssh keys.

See [issue #9](https://github.com/markomarkovic/simple-php-git-deploy/issues/9) for more info, and [this comment](https://github.com/markomarkovic/simple-php-git-deploy/issues/6#issuecomment-32053092) for a possible solution. Just make sure you're using `apache` instead of `www-data` user, when trying these.

**Comment by micjamking** [comment]
@markomarkovic not sure which step resolved the issue, but following [that comment](https://github.com/markomarkovic/simple-php-git-deploy/issues/6#issuecomment-32053092) you recommended did the trick! Appreciate the help!
