### ISSUE TITLE
Git not available.

### ISSUE THREAD

**Issue by mxxcon** [markomarkovic/simple-php-git-deploy#56]
Running CentOS7, simple-php-git-deploy 1.3.1
```
# git --version
git version 1.8.3.1
```
However, github webhook log shows
```
Checking the environment ...

Running as <b>nginx</b>.

<div class="error"><b>git</b> not available. It needs to be installed on the server for this script to work.</div>
```

**Comment by hdytsgt** [comment]
@mxxcon Quickest fix probably use your git full path

# which git
/usr/local/bin/git

Then change every git call in deploy.php line : 197, 235, 244, 250, 258, 264 
into something like : /usr/local/bin/git clone --depth=1 --branch %s %s %s

**Comment by doidd** [comment]
@hdytsgt  That’s a good idea. I have save problem with centos 5.11. I change every git call in deploy.php
>git clone --depth=1 --branch %s %s %s 
to 
  > /usr/local/bin/git clone --depth=1 --branch %s %s %s
And important change 
```php
$requiredBinaries = array('git', 'rsync');
```
to 
```php
$requiredBinaries = array();
```
or you can delete 
```php
foreach ($requiredBinaries as $command) {
  $path = trim(shell_exec('which '.$command));
  if ($path == '') {
    die(sprintf('<div class="error"><b>%s</b> not available. It needs to be installed on the server for this script to work.</div>', $command));
  } else {
    $version = explode("\n", shell_exec($command.' --version'));
    printf('<b>%s</b> : %s'."\n"
      , $path
      , $version[0]
    );
  }
}
```

**Comment by maxmatthews** [comment]
I know this is an old issue, but using the solution in this ticket fixed running this script in NameCheap's shared hosting after enabling `shell_exec` in your `php.ini` using these links: https://www.namecheap.com/support/knowledgebase/article.aspx/9396/2219/how-to-enable-exec and https://www.namecheap.com/support/knowledgebase/article.aspx/9314
Just wanted to share in case anyone else runs across the issue.
