### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bblue** [markomarkovic/simple-php-git-deploy#64]
After some hassle I finally managed to use this library on a windows server 2008 R2. I eventually gave up using rsync due to file permission issues in NTFS, and I am now using a simpler robocopy snip instead. I also changed from tar to 7z as 7z has better support in windows.

I can put my changes in a commit and make a pull request if there's any chance of it being merged.

**Comment by markomarkovic** [comment]
Sorry, I don't think it'll be merged, but feel free to fork and do your own thing.
