### ISSUE TITLE
Support for multiple repos

### ISSUE THREAD

**Issue by comvice** [markomarkovic/simple-php-git-deploy#69]
Hi, can you please add support for auto deploy multiple repo's?
For example, adding an array into the config file.
And provide a additional GET parameter for selecting the target repo like the array index (reduce traffic).

I think it's a bad practise for placing in every repo the 2 files (`deploy.php` and `deploy-config.php`)

**Comment by markomarkovic** [comment]
No, sorry. The script is primarily intended to be **simple** and I feel that a change like that is going to complicate it needlessly, as there's already a relatively simple way to achieve the same functionality (by having multiple scripts, configured differently).

Feel free to fork it and implement the changes you need yourself.

**Comment by markomarkovic** [comment]
Considering "bad practise for placing in every repo the 2 files", you don't _need_ to have two files as you can configure everything in `deploy.php` directly and have just that one file there.
