### ISSUE TITLE
Improve the code for multi branches deploy

### ISSUE THREAD

**Issue by vinhtq** [markomarkovic/simple-php-git-deploy#74]
I think the solution is not flexible enough for multi branch deploy.

Git hooks just allow one url for each repository
So imagine I have many branches in one repository how can I do that?

Suppose I will do something like this:

Git hooks I will input : `example.com/deploy.php?salt=somethinghere`

Then in the server i created two files: `deploy.php` and `deploy-config.php`
for deploying to `/var/www/html/example.com`

what about I want a brazil branch for deploying in `/var/www/html/example.com.br` with the same repo.

Im stuck here right?

**Comment by markomarkovic** [comment]
GitHub does allow only one URL per webhook, but it allows multiple webhooks. Simply add multiple deploy scripts (as described in the [Tips'n'Tricks](https://github.com/markomarkovic/simple-php-git-deploy#tipsntricks) section), and add multiple webhooks targeting these scripts.
