### ISSUE TITLE
Use custom commands.

### ISSUE THREAD

**Issue by WMontagnon** [markomarkovic/simple-php-git-deploy#75]
What do you think about adding the possibility to run custom commands, like running SQL scripts stored in a folder, update some libraries, etc ?

**Comment by markomarkovic** [comment]
It's certainly doable, but I wouldn't want the script to become **not-so-**simple-php-git-deploy :smile:. You can always add your own post-deployment steps, or perhaps use composer and its scripts system to do database migrations or whatever.

**Comment by cavo789** [comment]
Hi Marko

I was facing the same question : being able to run a "post deployment" custom script.  

I agree with your remark here below but, please, is it possible to foresee a parameter in deploy-config.php, just like for the email : if empty, do nothing, if specified, the value should be a PHP filename and, in your code, it will be only one line to add.

Something like : 

```diff

// =======================================[ Post-Deployment steps ]===

// Remove the TMP_DIR (depends on CLEAN_UP)
if (CLEAN_UP) {
	$commands['cleanup'] = sprintf(
		'rm -rf %s'
		, TMP_DIR
	);
}

+if (defined('AFTER_DEPLOY') && AFTER_DEPLOY === true) $commands['after-deploy']='php '.TARGET_DIR.'deploy-done.php '.SECRET_ACCESS_TOKEN;

// =======================================[ Run the command steps ]===
```

The idea : being able to specify a custom script, you check that the script exists, is a php and so on and if fine, run it.

Today, I've thus hack your code, just one line but I'll loose my modification when I'll download your latest version.

Is it possible ?

Thank you !

(and thank you too for your great script)
