### ISSUE TITLE
When i delete file from my gihub repo the file was not deleted from the server

### ISSUE THREAD

**Issue by aa-ahmed-aa** [markomarkovic/simple-php-git-deploy#87]
after i commit my changes to github (those changes contains files deletion ) that commit was not applied to the server and the file still exists

**Comment by markomarkovic** [comment]
Have you configured the [`DELETE_FILES`](https://github.com/markomarkovic/simple-php-git-deploy/blob/master/deploy-config.example.php#L49-L60) (to enable deletion) and [`EXCLUDE`](https://github.com/markomarkovic/simple-php-git-deploy/blob/master/deploy-config.example.php#L62-L72) (to not delete files you wish to keep) options?

**Comment by aa-ahmed-aa** [comment]
i think this should be
