### ISSUE TITLE
Help: Access Denied!

### ISSUE THREAD

**Issue by duceduc** [markomarkovic/simple-php-git-deploy#88]
When I try to access the url, I get an Access Denied! in red. I can't figure out what I am doing wrong. I have tried changing file/folder permission to 777, chown to www-data,

**Comment by markomarkovic** [comment]
Have you [configured the script](https://github.com/markomarkovic/simple-php-git-deploy#usage), changed [`SECRET_ACCESS_TOKEN`](https://github.com/markomarkovic/simple-php-git-deploy/blob/master/deploy-config.example.php#L15-L22), and you're using it in the URL?

**Comment by duceduc** [comment]
Yes. I figured it out. The Access token can only be alphanumeric. Github doesn't parse special characters.

My next issue is rsync errors.

rsync: chgrp "/home/ws1/www/github/user.github.io/." failed: Operation not permitted (1)
rsync: chgrp "/home/ws1/www/github/user.github.io/pihole" failed: Operation not permitted (1)

**Comment by duceduc** [comment]
Update: 
Got it. Need to chown to the system user. Script run with no errors. Thanks.
